# CC = g++
CFLAGS = -Wall -g

# server port
PORT = 1234

# server IP
IP_SERVER = 127.0.0.1

all: server subscriber

server: server.cpp

subscriber: subscriber.cpp

clean:
	rm -f server subscriber

.PHONY: clean